Fix building packages with bin targets
I have a cross-platform application that needs to build a bin target on Windows, macOS, and Linux (at minimum).
`cargo-apk` attempts to build my bin target as a `cdylib`, and explodes after signing:

```
thread 'main' panicked at /home/jay/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-subcommand-0.12.0/src/artifact.rs:51:23:
Bin is not compatible with Cdylib
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: cargo_subcommand::artifact::Artifact::file_name
   3: cargo_subcommand::subcommand::Subcommand::artifact
   4: cargo_apk::apk::ApkBuilder::build
   5: cargo_apk::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This fixes the panic by filtering artifacts to only build libraries.